### ISSUE TITLE
failed to create testdata/sample_genome.bed.gz

### ISSUE THREAD

**Issue by yuyzha** [ernstlab/csrep#2]
Hej! 

Thanks for releasing the powerful tools. I kept encountering an error following the tutorial by your testdata:

> [Mon Jun 26 10:45:17 2023]
> rule sample_genome:
>     input: testdata/roadmap_18state_chromlength.bed
>     output: testdata/sample_genome.bed.gz
>     jobid: 5
>     reason: Missing output files: testdata/sample_genome.bed.gz
>     resources: tmpdir=/tmp

I changed my working dictionary to ~/csrep$ already, and activated the conda env which was created using 

> conda env create -f env/csrep_env.yml 

I am running the code on buntu 20.04.6 LTS and python version is 3.10.12.

Any suggestion would be highty appreciated! 

Best wishes,
Yuyang

![image](https://github.com/ernstlab/csrep/assets/19903122/818ed19a-d80b-4cf6-b10f-921754753084)

**Comment by havu73** [comment]
Hi Yuyang! Thank you so much for using our tools. I saw that you have closed the ticket. Does that mean your program finished running? One suggestion that i have based on your error report is that it is possible the program finished running to generate ```sample_genome.bed.gz```. However, there can be some latency between the moment the snakemake realizes the program finishes between the moment the file ```sample_genome.bed.gz``` actually get fully written out. Therefore, snakemake may try to run the next job in the pipeline but realize that the  file ```sample_genome.bed.gz``` is not there YET, and gives out the error. Solution: (1) rerun snakemake --> it will know where to pick up where it last finished, so no jobs get rerun wastefully. (2) add the flag ```--latency-wait SECONDS``` (replace SECONDS with a number, I think 30 may be enough) to tell snakemake that between jobs, allow a SECONDS seconds wait before running the next job. References: https://snakemake.readthedocs.io/en/v5.1.4/executable.html

Thank you! I hope that helps and let us know if any other issues arise!
